version: '3.8'

services:
   frontend:
      image: node:20
      ports:
         - 3000:3000
      volumes:
         - ./:/app
      working_dir: /app
      command: npm run setup
      networks:
         - projet-02-pet-foster-connect-back_backend-network

networks:
   projet-02-pet-foster-connect-back_backend-network:
      external: true
