version: '3.8'

services:
   frontend:
      build: .
      ports:
         - 3000:3000
      volumes:
         - .:/app
         - /app/node_modules
      networks:
         - projet-02-pet-foster-connect-back_backend-network

networks:
   projet-02-pet-foster-connect-back_backend-network:
      external: true
